# Name your service using format rws-[servicename]-service
service: rws-example-service
provider:
# The following should stay as is unless specific customisations are required
  name: aws
  runtime: nodejs10.x
  profile: ${opt:profile}
  region: ap-southeast-1
  stage: develop
  stackTags:
    Name: ${self:service}
    service_name: ${self:service}
    environment: ${self:provider.stage}
    managed_by: sls
functions:
  exampleFunction:
    tags:
      Name: ${self:service}-function-exampleFunction
      infrastructure_tier: Lambda
    iamRoleStatementsName: ${self:service}-exampleFunction-IAMRole-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - resource:action
        Resource: '*'
    handler: src/functions/exampleFunction.exampleFunction
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: example
          method: get
          cors: true
plugins:
  - serverless-tag-api-gateway
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
  - serverless-mocha-plugin
custom:
  serverless-mocha-plugin:
    testTemplate: templates/testTemplate.ejs
    functionTemplate: templates/functionTemplate.ejs
  apiGatewayTags:
    Name: ${self:service}-APIGateway
    environment: ${self:provider.stage}
    managed_by: sls
    stackName: ${self:service}
    infrastructure_tier: APIGateway
